// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ise.deviceadmin.outputs;

import com.pulumi.core.annotations.CustomType;
import java.util.Objects;

@CustomType
public final class GetAuthorizationExceptionRuleChildrenChildrenChildrenChildrenChildrenChildren {
    private GetAuthorizationExceptionRuleChildrenChildrenChildrenChildrenChildrenChildren() {}

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAuthorizationExceptionRuleChildrenChildrenChildrenChildrenChildrenChildren defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        public Builder() {}
        public Builder(GetAuthorizationExceptionRuleChildrenChildrenChildrenChildrenChildrenChildren defaults) {
    	      Objects.requireNonNull(defaults);
        }

        public GetAuthorizationExceptionRuleChildrenChildrenChildrenChildrenChildrenChildren build() {
            final var _resultValue = new GetAuthorizationExceptionRuleChildrenChildrenChildrenChildrenChildrenChildren();
            return _resultValue;
        }
    }
}
