// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ise.ActiveDirectoryJoin;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.ise.ActiveDirectoryJoin.PointArgs;
import com.pulumi.ise.ActiveDirectoryJoin.inputs.PointState;
import com.pulumi.ise.ActiveDirectoryJoin.outputs.PointAttribute;
import com.pulumi.ise.ActiveDirectoryJoin.outputs.PointGroup;
import com.pulumi.ise.ActiveDirectoryJoin.outputs.PointRewriteRule;
import com.pulumi.ise.Utilities;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * This resource can manage an Active Directory Join Point.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.ise.ActiveDirectoryJoin.Point;
 * import com.pulumi.ise.ActiveDirectoryJoin.PointArgs;
 * import com.pulumi.ise.ActiveDirectoryJoin.inputs.PointGroupArgs;
 * import com.pulumi.ise.ActiveDirectoryJoin.inputs.PointAttributeArgs;
 * import com.pulumi.ise.ActiveDirectoryJoin.inputs.PointRewriteRuleArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new Point(&#34;example&#34;, PointArgs.builder()        
 *             .name(&#34;cisco.local&#34;)
 *             .description(&#34;My AD join point&#34;)
 *             .domain(&#34;cisco.local&#34;)
 *             .adScopesNames(&#34;Default_Scope&#34;)
 *             .enableDomainAllowedList(true)
 *             .groups(PointGroupArgs.builder()
 *                 .name(&#34;cisco.local/operators&#34;)
 *                 .sid(&#34;S-1-5-32-548&#34;)
 *                 .type(&#34;GLOBAL&#34;)
 *                 .build())
 *             .attributes(PointAttributeArgs.builder()
 *                 .name(&#34;Attribute_1&#34;)
 *                 .type(&#34;STRING&#34;)
 *                 .internal_name(&#34;internal_name&#34;)
 *                 .default_value(&#34;default_string&#34;)
 *                 .build())
 *             .rewriteRules(PointRewriteRuleArgs.builder()
 *                 .row_id(&#34;0&#34;)
 *                 .rewrite_match(&#34;rewrite_match&#34;)
 *                 .rewrite_result(&#34;rewrite_result&#34;)
 *                 .build())
 *             .enableRewrites(false)
 *             .enablePassChange(true)
 *             .enableMachineAuth(true)
 *             .enableMachineAccess(true)
 *             .enableDialinPermissionCheck(false)
 *             .plaintextAuth(false)
 *             .agingTime(5)
 *             .enableCallbackForDialinClient(false)
 *             .identityNotInAdBehaviour(&#34;SEARCH_JOINED_FOREST&#34;)
 *             .unreachableDomainsBehaviour(&#34;PROCEED&#34;)
 *             .schema(&#34;ACTIVE_DIRECTORY&#34;)
 *             .firstName(&#34;givenName&#34;)
 *             .department(&#34;department&#34;)
 *             .lastName(&#34;sn&#34;)
 *             .organizationalUnit(&#34;company&#34;)
 *             .jobTitle(&#34;title&#34;)
 *             .locality(&#34;l&#34;)
 *             .email(&#34;mail&#34;)
 *             .stateOrProvince(&#34;st&#34;)
 *             .telephone(&#34;telephoneNumber&#34;)
 *             .country(&#34;co&#34;)
 *             .streetAddress(&#34;streetAddress&#34;)
 *             .enableFailedAuthProtection(false)
 *             .failedAuthThreshold(5)
 *             .authProtectionType(&#34;WIRELESS&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import ise:ActiveDirectoryJoin/point:Point example &#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;
 * ```
 * 
 */
@ResourceType(type="ise:ActiveDirectoryJoin/point:Point")
public class Point extends com.pulumi.resources.CustomResource {
    /**
     * String that contains the names of the scopes that the active directory belongs to. Names are separated by comma. -
     * Default value: `Default_Scope`
     * 
     */
    @Export(name="adScopesNames", refs={String.class}, tree="[0]")
    private Output<String> adScopesNames;

    /**
     * @return String that contains the names of the scopes that the active directory belongs to. Names are separated by comma. -
     * Default value: `Default_Scope`
     * 
     */
    public Output<String> adScopesNames() {
        return this.adScopesNames;
    }
    /**
     * Aging Time - Default value: `5`
     * 
     */
    @Export(name="agingTime", refs={Integer.class}, tree="[0]")
    private Output<Integer> agingTime;

    /**
     * @return Aging Time - Default value: `5`
     * 
     */
    public Output<Integer> agingTime() {
        return this.agingTime;
    }
    /**
     * List of AD attributes
     * 
     */
    @Export(name="attributes", refs={List.class,PointAttribute.class}, tree="[0,1]")
    private Output</* @Nullable */ List<PointAttribute>> attributes;

    /**
     * @return List of AD attributes
     * 
     */
    public Output<Optional<List<PointAttribute>>> attributes() {
        return Codegen.optional(this.attributes);
    }
    /**
     * Enable prevent AD account lockout for WIRELESS/WIRED/BOTH - Choices: `WIRELESS`, `WIRED`, `BOTH`
     * 
     */
    @Export(name="authProtectionType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> authProtectionType;

    /**
     * @return Enable prevent AD account lockout for WIRELESS/WIRED/BOTH - Choices: `WIRELESS`, `WIRED`, `BOTH`
     * 
     */
    public Output<Optional<String>> authProtectionType() {
        return Codegen.optional(this.authProtectionType);
    }
    /**
     * User info attribute
     * 
     */
    @Export(name="country", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> country;

    /**
     * @return User info attribute
     * 
     */
    public Output<Optional<String>> country() {
        return Codegen.optional(this.country);
    }
    /**
     * User info attribute
     * 
     */
    @Export(name="department", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> department;

    /**
     * @return User info attribute
     * 
     */
    public Output<Optional<String>> department() {
        return Codegen.optional(this.department);
    }
    /**
     * Join point description
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Join point description
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * AD domain associated with the join point
     * 
     */
    @Export(name="domain", refs={String.class}, tree="[0]")
    private Output<String> domain;

    /**
     * @return AD domain associated with the join point
     * 
     */
    public Output<String> domain() {
        return this.domain;
    }
    /**
     * User info attribute
     * 
     */
    @Export(name="email", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> email;

    /**
     * @return User info attribute
     * 
     */
    public Output<Optional<String>> email() {
        return Codegen.optional(this.email);
    }
    /**
     * Enable Callback For Dial In Client - Default value: `false`
     * 
     */
    @Export(name="enableCallbackForDialinClient", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enableCallbackForDialinClient;

    /**
     * @return Enable Callback For Dial In Client - Default value: `false`
     * 
     */
    public Output<Boolean> enableCallbackForDialinClient() {
        return this.enableCallbackForDialinClient;
    }
    /**
     * Enable Dial In Permission Check - Default value: `false`
     * 
     */
    @Export(name="enableDialinPermissionCheck", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enableDialinPermissionCheck;

    /**
     * @return Enable Dial In Permission Check - Default value: `false`
     * 
     */
    public Output<Boolean> enableDialinPermissionCheck() {
        return this.enableDialinPermissionCheck;
    }
    /**
     * - Default value: `true`
     * 
     */
    @Export(name="enableDomainAllowedList", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enableDomainAllowedList;

    /**
     * @return - Default value: `true`
     * 
     */
    public Output<Boolean> enableDomainAllowedList() {
        return this.enableDomainAllowedList;
    }
    /**
     * Enable prevent AD account lockout due to too many bad password attempts - Default value: `false`
     * 
     */
    @Export(name="enableFailedAuthProtection", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enableFailedAuthProtection;

    /**
     * @return Enable prevent AD account lockout due to too many bad password attempts - Default value: `false`
     * 
     */
    public Output<Boolean> enableFailedAuthProtection() {
        return this.enableFailedAuthProtection;
    }
    /**
     * Enable Machine Access - Default value: `true`
     * 
     */
    @Export(name="enableMachineAccess", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enableMachineAccess;

    /**
     * @return Enable Machine Access - Default value: `true`
     * 
     */
    public Output<Boolean> enableMachineAccess() {
        return this.enableMachineAccess;
    }
    /**
     * Enable Machine Authentication - Default value: `true`
     * 
     */
    @Export(name="enableMachineAuth", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enableMachineAuth;

    /**
     * @return Enable Machine Authentication - Default value: `true`
     * 
     */
    public Output<Boolean> enableMachineAuth() {
        return this.enableMachineAuth;
    }
    /**
     * Enable Password Change - Default value: `true`
     * 
     */
    @Export(name="enablePassChange", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enablePassChange;

    /**
     * @return Enable Password Change - Default value: `true`
     * 
     */
    public Output<Boolean> enablePassChange() {
        return this.enablePassChange;
    }
    /**
     * Enable Rewrites - Default value: `false`
     * 
     */
    @Export(name="enableRewrites", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enableRewrites;

    /**
     * @return Enable Rewrites - Default value: `false`
     * 
     */
    public Output<Boolean> enableRewrites() {
        return this.enableRewrites;
    }
    /**
     * Number of bad password attempts - Default value: `5`
     * 
     */
    @Export(name="failedAuthThreshold", refs={Integer.class}, tree="[0]")
    private Output<Integer> failedAuthThreshold;

    /**
     * @return Number of bad password attempts - Default value: `5`
     * 
     */
    public Output<Integer> failedAuthThreshold() {
        return this.failedAuthThreshold;
    }
    /**
     * User info attribute
     * 
     */
    @Export(name="firstName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> firstName;

    /**
     * @return User info attribute
     * 
     */
    public Output<Optional<String>> firstName() {
        return Codegen.optional(this.firstName);
    }
    /**
     * List of AD Groups
     * 
     */
    @Export(name="groups", refs={List.class,PointGroup.class}, tree="[0,1]")
    private Output</* @Nullable */ List<PointGroup>> groups;

    /**
     * @return List of AD Groups
     * 
     */
    public Output<Optional<List<PointGroup>>> groups() {
        return Codegen.optional(this.groups);
    }
    /**
     * Identity Not In AD Behaviour - Choices: `REJECT`, `SEARCH_JOINED_FOREST`, `SEARCH_ALL`
     * 
     */
    @Export(name="identityNotInAdBehaviour", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> identityNotInAdBehaviour;

    /**
     * @return Identity Not In AD Behaviour - Choices: `REJECT`, `SEARCH_JOINED_FOREST`, `SEARCH_ALL`
     * 
     */
    public Output<Optional<String>> identityNotInAdBehaviour() {
        return Codegen.optional(this.identityNotInAdBehaviour);
    }
    /**
     * User info attribute
     * 
     */
    @Export(name="jobTitle", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> jobTitle;

    /**
     * @return User info attribute
     * 
     */
    public Output<Optional<String>> jobTitle() {
        return Codegen.optional(this.jobTitle);
    }
    /**
     * User info attribute
     * 
     */
    @Export(name="lastName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastName;

    /**
     * @return User info attribute
     * 
     */
    public Output<Optional<String>> lastName() {
        return Codegen.optional(this.lastName);
    }
    /**
     * User info attribute
     * 
     */
    @Export(name="locality", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> locality;

    /**
     * @return User info attribute
     * 
     */
    public Output<Optional<String>> locality() {
        return Codegen.optional(this.locality);
    }
    /**
     * The name of the active directory join point
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the active directory join point
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * User info attribute
     * 
     */
    @Export(name="organizationalUnit", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> organizationalUnit;

    /**
     * @return User info attribute
     * 
     */
    public Output<Optional<String>> organizationalUnit() {
        return Codegen.optional(this.organizationalUnit);
    }
    /**
     * Plain Text Authentication - Default value: `false`
     * 
     */
    @Export(name="plaintextAuth", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> plaintextAuth;

    /**
     * @return Plain Text Authentication - Default value: `false`
     * 
     */
    public Output<Boolean> plaintextAuth() {
        return this.plaintextAuth;
    }
    /**
     * List of Rewrite rules
     * 
     */
    @Export(name="rewriteRules", refs={List.class,PointRewriteRule.class}, tree="[0,1]")
    private Output</* @Nullable */ List<PointRewriteRule>> rewriteRules;

    /**
     * @return List of Rewrite rules
     * 
     */
    public Output<Optional<List<PointRewriteRule>>> rewriteRules() {
        return Codegen.optional(this.rewriteRules);
    }
    /**
     * Schema - Choices: `ACTIVE_DIRECTORY`, `CUSTOM`
     * 
     */
    @Export(name="schema", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> schema;

    /**
     * @return Schema - Choices: `ACTIVE_DIRECTORY`, `CUSTOM`
     * 
     */
    public Output<Optional<String>> schema() {
        return Codegen.optional(this.schema);
    }
    /**
     * User info attribute
     * 
     */
    @Export(name="stateOrProvince", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> stateOrProvince;

    /**
     * @return User info attribute
     * 
     */
    public Output<Optional<String>> stateOrProvince() {
        return Codegen.optional(this.stateOrProvince);
    }
    /**
     * User info attribute
     * 
     */
    @Export(name="streetAddress", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> streetAddress;

    /**
     * @return User info attribute
     * 
     */
    public Output<Optional<String>> streetAddress() {
        return Codegen.optional(this.streetAddress);
    }
    /**
     * User info attribute
     * 
     */
    @Export(name="telephone", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> telephone;

    /**
     * @return User info attribute
     * 
     */
    public Output<Optional<String>> telephone() {
        return Codegen.optional(this.telephone);
    }
    /**
     * Unreachable Domains Behaviour - Choices: `PROCEED`, `DROP`
     * 
     */
    @Export(name="unreachableDomainsBehaviour", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> unreachableDomainsBehaviour;

    /**
     * @return Unreachable Domains Behaviour - Choices: `PROCEED`, `DROP`
     * 
     */
    public Output<Optional<String>> unreachableDomainsBehaviour() {
        return Codegen.optional(this.unreachableDomainsBehaviour);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Point(String name) {
        this(name, PointArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Point(String name, PointArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Point(String name, PointArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ise:ActiveDirectoryJoin/point:Point", name, args == null ? PointArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Point(String name, Output<String> id, @Nullable PointState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ise:ActiveDirectoryJoin/point:Point", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Point get(String name, Output<String> id, @Nullable PointState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Point(name, id, state, options);
    }
}
