// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ise.identitymanagement;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.ise.Utilities;
import com.pulumi.ise.identitymanagement.inputs.GetActiveDirectoryGroupsByDomainArgs;
import com.pulumi.ise.identitymanagement.inputs.GetActiveDirectoryGroupsByDomainPlainArgs;
import com.pulumi.ise.identitymanagement.inputs.GetActiveDirectoryJoinPointArgs;
import com.pulumi.ise.identitymanagement.inputs.GetActiveDirectoryJoinPointPlainArgs;
import com.pulumi.ise.identitymanagement.inputs.GetCertificateAuthenticationProfileArgs;
import com.pulumi.ise.identitymanagement.inputs.GetCertificateAuthenticationProfilePlainArgs;
import com.pulumi.ise.identitymanagement.inputs.GetEndpointArgs;
import com.pulumi.ise.identitymanagement.inputs.GetEndpointIdentityGroupArgs;
import com.pulumi.ise.identitymanagement.inputs.GetEndpointIdentityGroupPlainArgs;
import com.pulumi.ise.identitymanagement.inputs.GetEndpointPlainArgs;
import com.pulumi.ise.identitymanagement.inputs.GetIdentitySourceSequenceArgs;
import com.pulumi.ise.identitymanagement.inputs.GetIdentitySourceSequencePlainArgs;
import com.pulumi.ise.identitymanagement.inputs.GetInternalUserArgs;
import com.pulumi.ise.identitymanagement.inputs.GetInternalUserPlainArgs;
import com.pulumi.ise.identitymanagement.inputs.GetUserIdentityGroupArgs;
import com.pulumi.ise.identitymanagement.inputs.GetUserIdentityGroupPlainArgs;
import com.pulumi.ise.identitymanagement.outputs.GetActiveDirectoryGroupsByDomainResult;
import com.pulumi.ise.identitymanagement.outputs.GetActiveDirectoryJoinPointResult;
import com.pulumi.ise.identitymanagement.outputs.GetCertificateAuthenticationProfileResult;
import com.pulumi.ise.identitymanagement.outputs.GetEndpointIdentityGroupResult;
import com.pulumi.ise.identitymanagement.outputs.GetEndpointResult;
import com.pulumi.ise.identitymanagement.outputs.GetIdentitySourceSequenceResult;
import com.pulumi.ise.identitymanagement.outputs.GetInternalUserResult;
import com.pulumi.ise.identitymanagement.outputs.GetUserIdentityGroupResult;
import java.util.concurrent.CompletableFuture;

public final class IdentitymanagementFunctions {
    /**
     * This data source can read the Active Directory Groups By Domain.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetActiveDirectoryGroupsByDomainArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getActiveDirectoryGroupsByDomain(GetActiveDirectoryGroupsByDomainArgs.builder()
     *             .joinPointId(&#34;73808580-b6e6-11ee-8960-de6d7692bc40&#34;)
     *             .domain(&#34;cisco.com&#34;)
     *             .filter(&#34;CN=ISE Admins&#34;)
     *             .sidFilter(&#34;cisco.com/S-1-5-33-544&#34;)
     *             .typeFilter(&#34;UNIVERSAL&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetActiveDirectoryGroupsByDomainResult> getActiveDirectoryGroupsByDomain(GetActiveDirectoryGroupsByDomainArgs args) {
        return getActiveDirectoryGroupsByDomain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Active Directory Groups By Domain.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetActiveDirectoryGroupsByDomainArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getActiveDirectoryGroupsByDomain(GetActiveDirectoryGroupsByDomainArgs.builder()
     *             .joinPointId(&#34;73808580-b6e6-11ee-8960-de6d7692bc40&#34;)
     *             .domain(&#34;cisco.com&#34;)
     *             .filter(&#34;CN=ISE Admins&#34;)
     *             .sidFilter(&#34;cisco.com/S-1-5-33-544&#34;)
     *             .typeFilter(&#34;UNIVERSAL&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetActiveDirectoryGroupsByDomainResult> getActiveDirectoryGroupsByDomainPlain(GetActiveDirectoryGroupsByDomainPlainArgs args) {
        return getActiveDirectoryGroupsByDomainPlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Active Directory Groups By Domain.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetActiveDirectoryGroupsByDomainArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getActiveDirectoryGroupsByDomain(GetActiveDirectoryGroupsByDomainArgs.builder()
     *             .joinPointId(&#34;73808580-b6e6-11ee-8960-de6d7692bc40&#34;)
     *             .domain(&#34;cisco.com&#34;)
     *             .filter(&#34;CN=ISE Admins&#34;)
     *             .sidFilter(&#34;cisco.com/S-1-5-33-544&#34;)
     *             .typeFilter(&#34;UNIVERSAL&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetActiveDirectoryGroupsByDomainResult> getActiveDirectoryGroupsByDomain(GetActiveDirectoryGroupsByDomainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:identitymanagement/getActiveDirectoryGroupsByDomain:getActiveDirectoryGroupsByDomain", TypeShape.of(GetActiveDirectoryGroupsByDomainResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Active Directory Groups By Domain.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetActiveDirectoryGroupsByDomainArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getActiveDirectoryGroupsByDomain(GetActiveDirectoryGroupsByDomainArgs.builder()
     *             .joinPointId(&#34;73808580-b6e6-11ee-8960-de6d7692bc40&#34;)
     *             .domain(&#34;cisco.com&#34;)
     *             .filter(&#34;CN=ISE Admins&#34;)
     *             .sidFilter(&#34;cisco.com/S-1-5-33-544&#34;)
     *             .typeFilter(&#34;UNIVERSAL&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetActiveDirectoryGroupsByDomainResult> getActiveDirectoryGroupsByDomainPlain(GetActiveDirectoryGroupsByDomainPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:identitymanagement/getActiveDirectoryGroupsByDomain:getActiveDirectoryGroupsByDomain", TypeShape.of(GetActiveDirectoryGroupsByDomainResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Active Directory Join Point.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetActiveDirectoryJoinPointArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getActiveDirectoryJoinPoint(GetActiveDirectoryJoinPointArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetActiveDirectoryJoinPointResult> getActiveDirectoryJoinPoint(GetActiveDirectoryJoinPointArgs args) {
        return getActiveDirectoryJoinPoint(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Active Directory Join Point.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetActiveDirectoryJoinPointArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getActiveDirectoryJoinPoint(GetActiveDirectoryJoinPointArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetActiveDirectoryJoinPointResult> getActiveDirectoryJoinPointPlain(GetActiveDirectoryJoinPointPlainArgs args) {
        return getActiveDirectoryJoinPointPlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Active Directory Join Point.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetActiveDirectoryJoinPointArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getActiveDirectoryJoinPoint(GetActiveDirectoryJoinPointArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetActiveDirectoryJoinPointResult> getActiveDirectoryJoinPoint(GetActiveDirectoryJoinPointArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:identitymanagement/getActiveDirectoryJoinPoint:getActiveDirectoryJoinPoint", TypeShape.of(GetActiveDirectoryJoinPointResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Active Directory Join Point.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetActiveDirectoryJoinPointArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getActiveDirectoryJoinPoint(GetActiveDirectoryJoinPointArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetActiveDirectoryJoinPointResult> getActiveDirectoryJoinPointPlain(GetActiveDirectoryJoinPointPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:identitymanagement/getActiveDirectoryJoinPoint:getActiveDirectoryJoinPoint", TypeShape.of(GetActiveDirectoryJoinPointResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Certificate Authentication Profile.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetCertificateAuthenticationProfileArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getCertificateAuthenticationProfile(GetCertificateAuthenticationProfileArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetCertificateAuthenticationProfileResult> getCertificateAuthenticationProfile() {
        return getCertificateAuthenticationProfile(GetCertificateAuthenticationProfileArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Certificate Authentication Profile.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetCertificateAuthenticationProfileArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getCertificateAuthenticationProfile(GetCertificateAuthenticationProfileArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetCertificateAuthenticationProfileResult> getCertificateAuthenticationProfilePlain() {
        return getCertificateAuthenticationProfilePlain(GetCertificateAuthenticationProfilePlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Certificate Authentication Profile.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetCertificateAuthenticationProfileArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getCertificateAuthenticationProfile(GetCertificateAuthenticationProfileArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetCertificateAuthenticationProfileResult> getCertificateAuthenticationProfile(GetCertificateAuthenticationProfileArgs args) {
        return getCertificateAuthenticationProfile(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Certificate Authentication Profile.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetCertificateAuthenticationProfileArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getCertificateAuthenticationProfile(GetCertificateAuthenticationProfileArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetCertificateAuthenticationProfileResult> getCertificateAuthenticationProfilePlain(GetCertificateAuthenticationProfilePlainArgs args) {
        return getCertificateAuthenticationProfilePlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Certificate Authentication Profile.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetCertificateAuthenticationProfileArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getCertificateAuthenticationProfile(GetCertificateAuthenticationProfileArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetCertificateAuthenticationProfileResult> getCertificateAuthenticationProfile(GetCertificateAuthenticationProfileArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:identitymanagement/getCertificateAuthenticationProfile:getCertificateAuthenticationProfile", TypeShape.of(GetCertificateAuthenticationProfileResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Certificate Authentication Profile.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetCertificateAuthenticationProfileArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getCertificateAuthenticationProfile(GetCertificateAuthenticationProfileArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetCertificateAuthenticationProfileResult> getCertificateAuthenticationProfilePlain(GetCertificateAuthenticationProfilePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:identitymanagement/getCertificateAuthenticationProfile:getCertificateAuthenticationProfile", TypeShape.of(GetCertificateAuthenticationProfileResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Endpoint.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetEndpointArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getEndpoint(GetEndpointArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetEndpointResult> getEndpoint() {
        return getEndpoint(GetEndpointArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Endpoint.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetEndpointArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getEndpoint(GetEndpointArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetEndpointResult> getEndpointPlain() {
        return getEndpointPlain(GetEndpointPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Endpoint.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetEndpointArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getEndpoint(GetEndpointArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetEndpointResult> getEndpoint(GetEndpointArgs args) {
        return getEndpoint(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Endpoint.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetEndpointArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getEndpoint(GetEndpointArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetEndpointResult> getEndpointPlain(GetEndpointPlainArgs args) {
        return getEndpointPlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Endpoint.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetEndpointArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getEndpoint(GetEndpointArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetEndpointResult> getEndpoint(GetEndpointArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:identitymanagement/getEndpoint:getEndpoint", TypeShape.of(GetEndpointResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Endpoint.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetEndpointArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getEndpoint(GetEndpointArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetEndpointResult> getEndpointPlain(GetEndpointPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:identitymanagement/getEndpoint:getEndpoint", TypeShape.of(GetEndpointResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Endpoint Identity Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetEndpointIdentityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getEndpointIdentityGroup(GetEndpointIdentityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetEndpointIdentityGroupResult> getEndpointIdentityGroup() {
        return getEndpointIdentityGroup(GetEndpointIdentityGroupArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Endpoint Identity Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetEndpointIdentityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getEndpointIdentityGroup(GetEndpointIdentityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetEndpointIdentityGroupResult> getEndpointIdentityGroupPlain() {
        return getEndpointIdentityGroupPlain(GetEndpointIdentityGroupPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Endpoint Identity Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetEndpointIdentityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getEndpointIdentityGroup(GetEndpointIdentityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetEndpointIdentityGroupResult> getEndpointIdentityGroup(GetEndpointIdentityGroupArgs args) {
        return getEndpointIdentityGroup(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Endpoint Identity Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetEndpointIdentityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getEndpointIdentityGroup(GetEndpointIdentityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetEndpointIdentityGroupResult> getEndpointIdentityGroupPlain(GetEndpointIdentityGroupPlainArgs args) {
        return getEndpointIdentityGroupPlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Endpoint Identity Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetEndpointIdentityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getEndpointIdentityGroup(GetEndpointIdentityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetEndpointIdentityGroupResult> getEndpointIdentityGroup(GetEndpointIdentityGroupArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:identitymanagement/getEndpointIdentityGroup:getEndpointIdentityGroup", TypeShape.of(GetEndpointIdentityGroupResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Endpoint Identity Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetEndpointIdentityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getEndpointIdentityGroup(GetEndpointIdentityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetEndpointIdentityGroupResult> getEndpointIdentityGroupPlain(GetEndpointIdentityGroupPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:identitymanagement/getEndpointIdentityGroup:getEndpointIdentityGroup", TypeShape.of(GetEndpointIdentityGroupResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Identity Source Sequence.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetIdentitySourceSequenceArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getIdentitySourceSequence(GetIdentitySourceSequenceArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetIdentitySourceSequenceResult> getIdentitySourceSequence() {
        return getIdentitySourceSequence(GetIdentitySourceSequenceArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Identity Source Sequence.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetIdentitySourceSequenceArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getIdentitySourceSequence(GetIdentitySourceSequenceArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetIdentitySourceSequenceResult> getIdentitySourceSequencePlain() {
        return getIdentitySourceSequencePlain(GetIdentitySourceSequencePlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Identity Source Sequence.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetIdentitySourceSequenceArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getIdentitySourceSequence(GetIdentitySourceSequenceArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetIdentitySourceSequenceResult> getIdentitySourceSequence(GetIdentitySourceSequenceArgs args) {
        return getIdentitySourceSequence(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Identity Source Sequence.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetIdentitySourceSequenceArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getIdentitySourceSequence(GetIdentitySourceSequenceArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetIdentitySourceSequenceResult> getIdentitySourceSequencePlain(GetIdentitySourceSequencePlainArgs args) {
        return getIdentitySourceSequencePlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Identity Source Sequence.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetIdentitySourceSequenceArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getIdentitySourceSequence(GetIdentitySourceSequenceArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetIdentitySourceSequenceResult> getIdentitySourceSequence(GetIdentitySourceSequenceArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:identitymanagement/getIdentitySourceSequence:getIdentitySourceSequence", TypeShape.of(GetIdentitySourceSequenceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Identity Source Sequence.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetIdentitySourceSequenceArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getIdentitySourceSequence(GetIdentitySourceSequenceArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetIdentitySourceSequenceResult> getIdentitySourceSequencePlain(GetIdentitySourceSequencePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:identitymanagement/getIdentitySourceSequence:getIdentitySourceSequence", TypeShape.of(GetIdentitySourceSequenceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Internal User.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetInternalUserArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getInternalUser(GetInternalUserArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetInternalUserResult> getInternalUser() {
        return getInternalUser(GetInternalUserArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Internal User.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetInternalUserArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getInternalUser(GetInternalUserArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetInternalUserResult> getInternalUserPlain() {
        return getInternalUserPlain(GetInternalUserPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Internal User.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetInternalUserArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getInternalUser(GetInternalUserArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetInternalUserResult> getInternalUser(GetInternalUserArgs args) {
        return getInternalUser(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Internal User.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetInternalUserArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getInternalUser(GetInternalUserArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetInternalUserResult> getInternalUserPlain(GetInternalUserPlainArgs args) {
        return getInternalUserPlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the Internal User.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetInternalUserArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getInternalUser(GetInternalUserArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetInternalUserResult> getInternalUser(GetInternalUserArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:identitymanagement/getInternalUser:getInternalUser", TypeShape.of(GetInternalUserResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the Internal User.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetInternalUserArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getInternalUser(GetInternalUserArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetInternalUserResult> getInternalUserPlain(GetInternalUserPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:identitymanagement/getInternalUser:getInternalUser", TypeShape.of(GetInternalUserResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the User Identity Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetUserIdentityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getUserIdentityGroup(GetUserIdentityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetUserIdentityGroupResult> getUserIdentityGroup() {
        return getUserIdentityGroup(GetUserIdentityGroupArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the User Identity Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetUserIdentityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getUserIdentityGroup(GetUserIdentityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetUserIdentityGroupResult> getUserIdentityGroupPlain() {
        return getUserIdentityGroupPlain(GetUserIdentityGroupPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the User Identity Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetUserIdentityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getUserIdentityGroup(GetUserIdentityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetUserIdentityGroupResult> getUserIdentityGroup(GetUserIdentityGroupArgs args) {
        return getUserIdentityGroup(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the User Identity Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetUserIdentityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getUserIdentityGroup(GetUserIdentityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetUserIdentityGroupResult> getUserIdentityGroupPlain(GetUserIdentityGroupPlainArgs args) {
        return getUserIdentityGroupPlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the User Identity Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetUserIdentityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getUserIdentityGroup(GetUserIdentityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetUserIdentityGroupResult> getUserIdentityGroup(GetUserIdentityGroupArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:identitymanagement/getUserIdentityGroup:getUserIdentityGroup", TypeShape.of(GetUserIdentityGroupResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the User Identity Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.identitymanagement.IdentitymanagementFunctions;
     * import com.pulumi.ise.identitymanagement.inputs.GetUserIdentityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = IdentitymanagementFunctions.getUserIdentityGroup(GetUserIdentityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetUserIdentityGroupResult> getUserIdentityGroupPlain(GetUserIdentityGroupPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:identitymanagement/getUserIdentityGroup:getUserIdentityGroup", TypeShape.of(GetUserIdentityGroupResult.class), args, Utilities.withVersion(options));
    }
}
