// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package trustsec

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-ise/sdk/go/ise/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source can read the SXP Connection.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-ise/sdk/go/ise/trustsec"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := trustsec.LookupSxpConnection(ctx, &trustsec.LookupSxpConnectionArgs{
//				Id: pulumi.StringRef("76d24097-41c4-4558-a4d0-a8c07ac08470"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSxpConnection(ctx *pulumi.Context, args *LookupSxpConnectionArgs, opts ...pulumi.InvokeOption) (*LookupSxpConnectionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSxpConnectionResult
	err := ctx.Invoke("ise:trustsec/getSxpConnection:getSxpConnection", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSxpConnection.
type LookupSxpConnectionArgs struct {
	// The id of the object
	Id *string `pulumi:"id"`
	// The name of the SXP connection.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getSxpConnection.
type LookupSxpConnectionResult struct {
	// The description of the SXP connection
	Description string `pulumi:"description"`
	// Enables or disables the SXP connection.
	Enabled bool `pulumi:"enabled"`
	// The id of the object
	Id string `pulumi:"id"`
	// The IP address of the SXP peer.
	IpAddress string `pulumi:"ipAddress"`
	// The name of the SXP connection.
	Name string `pulumi:"name"`
	// The SXP connection mode
	SxpMode string `pulumi:"sxpMode"`
	// The name of the SXP node.
	SxpNode string `pulumi:"sxpNode"`
	// The name of the SXP peer.
	SxpPeer string `pulumi:"sxpPeer"`
	// The SXP protocol version negotiated with the peer
	SxpVersion string `pulumi:"sxpVersion"`
	// The name of the SXP VPN. Since Cisco ISE 3.0, a comma-separated list of multiple SXP VPN names is supported.
	SxpVpn string `pulumi:"sxpVpn"`
}

func LookupSxpConnectionOutput(ctx *pulumi.Context, args LookupSxpConnectionOutputArgs, opts ...pulumi.InvokeOption) LookupSxpConnectionResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("ise:trustsec/getSxpConnection:getSxpConnection", args, LookupSxpConnectionResultOutput{}, options).(LookupSxpConnectionResultOutput)
}

// A collection of arguments for invoking getSxpConnection.
type LookupSxpConnectionOutputArgs struct {
	// The id of the object
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The name of the SXP connection.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupSxpConnectionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSxpConnectionArgs)(nil)).Elem()
}

// A collection of values returned by getSxpConnection.
type LookupSxpConnectionResultOutput struct{ *pulumi.OutputState }

func (LookupSxpConnectionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSxpConnectionResult)(nil)).Elem()
}

func (o LookupSxpConnectionResultOutput) ToLookupSxpConnectionResultOutput() LookupSxpConnectionResultOutput {
	return o
}

func (o LookupSxpConnectionResultOutput) ToLookupSxpConnectionResultOutputWithContext(ctx context.Context) LookupSxpConnectionResultOutput {
	return o
}

// The description of the SXP connection
func (o LookupSxpConnectionResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSxpConnectionResult) string { return v.Description }).(pulumi.StringOutput)
}

// Enables or disables the SXP connection.
func (o LookupSxpConnectionResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSxpConnectionResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// The id of the object
func (o LookupSxpConnectionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSxpConnectionResult) string { return v.Id }).(pulumi.StringOutput)
}

// The IP address of the SXP peer.
func (o LookupSxpConnectionResultOutput) IpAddress() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSxpConnectionResult) string { return v.IpAddress }).(pulumi.StringOutput)
}

// The name of the SXP connection.
func (o LookupSxpConnectionResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSxpConnectionResult) string { return v.Name }).(pulumi.StringOutput)
}

// The SXP connection mode
func (o LookupSxpConnectionResultOutput) SxpMode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSxpConnectionResult) string { return v.SxpMode }).(pulumi.StringOutput)
}

// The name of the SXP node.
func (o LookupSxpConnectionResultOutput) SxpNode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSxpConnectionResult) string { return v.SxpNode }).(pulumi.StringOutput)
}

// The name of the SXP peer.
func (o LookupSxpConnectionResultOutput) SxpPeer() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSxpConnectionResult) string { return v.SxpPeer }).(pulumi.StringOutput)
}

// The SXP protocol version negotiated with the peer
func (o LookupSxpConnectionResultOutput) SxpVersion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSxpConnectionResult) string { return v.SxpVersion }).(pulumi.StringOutput)
}

// The name of the SXP VPN. Since Cisco ISE 3.0, a comma-separated list of multiple SXP VPN names is supported.
func (o LookupSxpConnectionResultOutput) SxpVpn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSxpConnectionResult) string { return v.SxpVpn }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSxpConnectionResultOutput{})
}
