# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_ise.activedirectory as __activedirectory
    activedirectory = __activedirectory
    import pulumi_ise.config as __config
    config = __config
    import pulumi_ise.deviceadmin as __deviceadmin
    deviceadmin = __deviceadmin
    import pulumi_ise.identity as __identity
    identity = __identity
    import pulumi_ise.network as __network
    network = __network
    import pulumi_ise.system as __system
    system = __system
    import pulumi_ise.tacacs as __tacacs
    tacacs = __tacacs
    import pulumi_ise.trustsec as __trustsec
    trustsec = __trustsec
else:
    activedirectory = _utilities.lazy_import('pulumi_ise.activedirectory')
    config = _utilities.lazy_import('pulumi_ise.config')
    deviceadmin = _utilities.lazy_import('pulumi_ise.deviceadmin')
    identity = _utilities.lazy_import('pulumi_ise.identity')
    network = _utilities.lazy_import('pulumi_ise.network')
    system = _utilities.lazy_import('pulumi_ise.system')
    tacacs = _utilities.lazy_import('pulumi_ise.tacacs')
    trustsec = _utilities.lazy_import('pulumi_ise.trustsec')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "ise",
  "mod": "activeDirectory/addGroups",
  "fqn": "pulumi_ise.activedirectory",
  "classes": {
   "ise:activeDirectory/addGroups:AddGroups": "AddGroups"
  }
 },
 {
  "pkg": "ise",
  "mod": "activeDirectory/joinDomainWithAllNodes",
  "fqn": "pulumi_ise.activedirectory",
  "classes": {
   "ise:activeDirectory/joinDomainWithAllNodes:JoinDomainWithAllNodes": "JoinDomainWithAllNodes"
  }
 },
 {
  "pkg": "ise",
  "mod": "activeDirectory/joinPoint",
  "fqn": "pulumi_ise.activedirectory",
  "classes": {
   "ise:activeDirectory/joinPoint:JoinPoint": "JoinPoint"
  }
 },
 {
  "pkg": "ise",
  "mod": "deviceAdmin/authenticationRule",
  "fqn": "pulumi_ise.deviceadmin",
  "classes": {
   "ise:deviceAdmin/authenticationRule:AuthenticationRule": "AuthenticationRule"
  }
 },
 {
  "pkg": "ise",
  "mod": "deviceAdmin/authorizationExceptionRule",
  "fqn": "pulumi_ise.deviceadmin",
  "classes": {
   "ise:deviceAdmin/authorizationExceptionRule:AuthorizationExceptionRule": "AuthorizationExceptionRule"
  }
 },
 {
  "pkg": "ise",
  "mod": "deviceAdmin/authorizationGlobalExceptionRule",
  "fqn": "pulumi_ise.deviceadmin",
  "classes": {
   "ise:deviceAdmin/authorizationGlobalExceptionRule:AuthorizationGlobalExceptionRule": "AuthorizationGlobalExceptionRule"
  }
 },
 {
  "pkg": "ise",
  "mod": "deviceAdmin/authorizationRule",
  "fqn": "pulumi_ise.deviceadmin",
  "classes": {
   "ise:deviceAdmin/authorizationRule:AuthorizationRule": "AuthorizationRule"
  }
 },
 {
  "pkg": "ise",
  "mod": "deviceAdmin/condition",
  "fqn": "pulumi_ise.deviceadmin",
  "classes": {
   "ise:deviceAdmin/condition:Condition": "Condition"
  }
 },
 {
  "pkg": "ise",
  "mod": "deviceAdmin/policySet",
  "fqn": "pulumi_ise.deviceadmin",
  "classes": {
   "ise:deviceAdmin/policySet:PolicySet": "PolicySet"
  }
 },
 {
  "pkg": "ise",
  "mod": "deviceAdmin/timeAndDateCondition",
  "fqn": "pulumi_ise.deviceadmin",
  "classes": {
   "ise:deviceAdmin/timeAndDateCondition:TimeAndDateCondition": "TimeAndDateCondition"
  }
 },
 {
  "pkg": "ise",
  "mod": "identity/certificateAuthenticationProfile",
  "fqn": "pulumi_ise.identity",
  "classes": {
   "ise:identity/certificateAuthenticationProfile:CertificateAuthenticationProfile": "CertificateAuthenticationProfile"
  }
 },
 {
  "pkg": "ise",
  "mod": "identity/endpoint",
  "fqn": "pulumi_ise.identity",
  "classes": {
   "ise:identity/endpoint:Endpoint": "Endpoint"
  }
 },
 {
  "pkg": "ise",
  "mod": "identity/endpointIdentityGroup",
  "fqn": "pulumi_ise.identity",
  "classes": {
   "ise:identity/endpointIdentityGroup:EndpointIdentityGroup": "EndpointIdentityGroup"
  }
 },
 {
  "pkg": "ise",
  "mod": "identity/identitySourceSequence",
  "fqn": "pulumi_ise.identity",
  "classes": {
   "ise:identity/identitySourceSequence:IdentitySourceSequence": "IdentitySourceSequence"
  }
 },
 {
  "pkg": "ise",
  "mod": "identity/internalUser",
  "fqn": "pulumi_ise.identity",
  "classes": {
   "ise:identity/internalUser:InternalUser": "InternalUser"
  }
 },
 {
  "pkg": "ise",
  "mod": "identity/userIdentityGroup",
  "fqn": "pulumi_ise.identity",
  "classes": {
   "ise:identity/userIdentityGroup:UserIdentityGroup": "UserIdentityGroup"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/accessAuthenticationRule",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/accessAuthenticationRule:AccessAuthenticationRule": "AccessAuthenticationRule"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/accessAuthorizationExceptionRule",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/accessAuthorizationExceptionRule:AccessAuthorizationExceptionRule": "AccessAuthorizationExceptionRule"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/accessAuthorizationGlobalExceptionRule",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/accessAuthorizationGlobalExceptionRule:AccessAuthorizationGlobalExceptionRule": "AccessAuthorizationGlobalExceptionRule"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/accessAuthorizationRule",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/accessAuthorizationRule:AccessAuthorizationRule": "AccessAuthorizationRule"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/accessCondition",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/accessCondition:AccessCondition": "AccessCondition"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/accessDictionary",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/accessDictionary:AccessDictionary": "AccessDictionary"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/accessPolicySet",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/accessPolicySet:AccessPolicySet": "AccessPolicySet"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/accessTimeAndDateCondition",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/accessTimeAndDateCondition:AccessTimeAndDateCondition": "AccessTimeAndDateCondition"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/allowedProtocols",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/allowedProtocols:AllowedProtocols": "AllowedProtocols"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/authorizationProfile",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/authorizationProfile:AuthorizationProfile": "AuthorizationProfile"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/device",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/device:Device": "Device"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/deviceGroup",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/deviceGroup:DeviceGroup": "DeviceGroup"
  }
 },
 {
  "pkg": "ise",
  "mod": "network/downloadableAcl",
  "fqn": "pulumi_ise.network",
  "classes": {
   "ise:network/downloadableAcl:DownloadableAcl": "DownloadableAcl"
  }
 },
 {
  "pkg": "ise",
  "mod": "system/licenseTierState",
  "fqn": "pulumi_ise.system",
  "classes": {
   "ise:system/licenseTierState:LicenseTierState": "LicenseTierState"
  }
 },
 {
  "pkg": "ise",
  "mod": "system/repository",
  "fqn": "pulumi_ise.system",
  "classes": {
   "ise:system/repository:Repository": "Repository"
  }
 },
 {
  "pkg": "ise",
  "mod": "tacacs/allowedProtocols",
  "fqn": "pulumi_ise.tacacs",
  "classes": {
   "ise:tacacs/allowedProtocols:AllowedProtocols": "AllowedProtocols"
  }
 },
 {
  "pkg": "ise",
  "mod": "tacacs/commandSet",
  "fqn": "pulumi_ise.tacacs",
  "classes": {
   "ise:tacacs/commandSet:CommandSet": "CommandSet"
  }
 },
 {
  "pkg": "ise",
  "mod": "tacacs/profile",
  "fqn": "pulumi_ise.tacacs",
  "classes": {
   "ise:tacacs/profile:Profile": "Profile"
  }
 },
 {
  "pkg": "ise",
  "mod": "trustsec/egressMatrixCell",
  "fqn": "pulumi_ise.trustsec",
  "classes": {
   "ise:trustsec/egressMatrixCell:EgressMatrixCell": "EgressMatrixCell"
  }
 },
 {
  "pkg": "ise",
  "mod": "trustsec/ipToSgtMapping",
  "fqn": "pulumi_ise.trustsec",
  "classes": {
   "ise:trustsec/ipToSgtMapping:IpToSgtMapping": "IpToSgtMapping"
  }
 },
 {
  "pkg": "ise",
  "mod": "trustsec/ipToSgtMappingGroup",
  "fqn": "pulumi_ise.trustsec",
  "classes": {
   "ise:trustsec/ipToSgtMappingGroup:IpToSgtMappingGroup": "IpToSgtMappingGroup"
  }
 },
 {
  "pkg": "ise",
  "mod": "trustsec/securityGroup",
  "fqn": "pulumi_ise.trustsec",
  "classes": {
   "ise:trustsec/securityGroup:SecurityGroup": "SecurityGroup"
  }
 },
 {
  "pkg": "ise",
  "mod": "trustsec/securityGroupAcl",
  "fqn": "pulumi_ise.trustsec",
  "classes": {
   "ise:trustsec/securityGroupAcl:SecurityGroupAcl": "SecurityGroupAcl"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "ise",
  "token": "pulumi:providers:ise",
  "fqn": "pulumi_ise",
  "class": "Provider"
 }
]
"""
)
