// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi-ise/sdk/go/ise/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Allow insecure HTTPS client. This can also be set as the ISE_INSECURE environment variable. Defaults to `true`.
func GetInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "ise:insecure")
}

// Password for the ISE instance. This can also be set as the ISE_PASSWORD environment variable.
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "ise:password")
}

// Number of retries for REST API calls. This can also be set as the ISE_RETRIES environment variable. Defaults to `3`.
func GetRetries(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "ise:retries")
}

// URL of the Cisco ISE instance. This can also be set as the ISE_URL environment variable.
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "ise:url")
}

// Username for the ISE instance. This can also be set as the ISE_USERNAME environment variable.
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "ise:username")
}
