// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package deviceadmin

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-ise/sdk/go/ise/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source can read the Device Admin Authorization Rule.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-ise/sdk/go/ise/deviceadmin"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := deviceadmin.LookupAuthorizationRule(ctx, &deviceadmin.LookupAuthorizationRuleArgs{
//				Id:          pulumi.StringRef("76d24097-41c4-4558-a4d0-a8c07ac08470"),
//				PolicySetId: "d82952cb-b901-4b09-b363-5ebf39bdbaf9",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupAuthorizationRule(ctx *pulumi.Context, args *LookupAuthorizationRuleArgs, opts ...pulumi.InvokeOption) (*LookupAuthorizationRuleResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAuthorizationRuleResult
	err := ctx.Invoke("ise:deviceadmin/getAuthorizationRule:getAuthorizationRule", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAuthorizationRule.
type LookupAuthorizationRuleArgs struct {
	// The id of the object
	Id *string `pulumi:"id"`
	// Rule name, [Valid characters are alphanumerics, underscore, hyphen, space, period, parentheses]
	Name *string `pulumi:"name"`
	// Policy set ID
	PolicySetId string `pulumi:"policySetId"`
}

// A collection of values returned by getAuthorizationRule.
type LookupAuthorizationRuleResult struct {
	// List of child conditions. `conditionType` must be one of `ConditionAndBlock` or `ConditionOrBlock`.
	Childrens []GetAuthorizationRuleChildren `pulumi:"childrens"`
	// Command sets enforce the specified list of commands that can be executed by a device administrator
	CommandSets []string `pulumi:"commandSets"`
	// Dictionary attribute name
	ConditionAttributeName string `pulumi:"conditionAttributeName"`
	// Attribute value for condition. Value type is specified in dictionary object.
	ConditionAttributeValue string `pulumi:"conditionAttributeValue"`
	// Dictionary name
	ConditionDictionaryName string `pulumi:"conditionDictionaryName"`
	// Dictionary value
	ConditionDictionaryValue string `pulumi:"conditionDictionaryValue"`
	// UUID for condition
	ConditionId string `pulumi:"conditionId"`
	// Indicates whereas this condition is in negate mode
	ConditionIsNegate bool `pulumi:"conditionIsNegate"`
	// Equality operator
	ConditionOperator string `pulumi:"conditionOperator"`
	// Indicates whether the record is the condition itself or a logical aggregation. Logical aggreation indicates that additional conditions are present under the children attribute.
	ConditionType string `pulumi:"conditionType"`
	// Indicates if this rule is the default one
	Default bool `pulumi:"default"`
	// The id of the object
	Id string `pulumi:"id"`
	// Rule name, [Valid characters are alphanumerics, underscore, hyphen, space, period, parentheses]
	Name string `pulumi:"name"`
	// Policy set ID
	PolicySetId string `pulumi:"policySetId"`
	// Device admin profiles control the initial login session of the device administrator
	Profile string `pulumi:"profile"`
	// The rank (priority) in relation to other rules. Lower rank is higher priority.
	Rank int `pulumi:"rank"`
	// The state that the rule is in. A disabled rule cannot be matched.
	State string `pulumi:"state"`
}

func LookupAuthorizationRuleOutput(ctx *pulumi.Context, args LookupAuthorizationRuleOutputArgs, opts ...pulumi.InvokeOption) LookupAuthorizationRuleResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupAuthorizationRuleResultOutput, error) {
			args := v.(LookupAuthorizationRuleArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("ise:deviceadmin/getAuthorizationRule:getAuthorizationRule", args, LookupAuthorizationRuleResultOutput{}, options).(LookupAuthorizationRuleResultOutput), nil
		}).(LookupAuthorizationRuleResultOutput)
}

// A collection of arguments for invoking getAuthorizationRule.
type LookupAuthorizationRuleOutputArgs struct {
	// The id of the object
	Id pulumi.StringPtrInput `pulumi:"id"`
	// Rule name, [Valid characters are alphanumerics, underscore, hyphen, space, period, parentheses]
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Policy set ID
	PolicySetId pulumi.StringInput `pulumi:"policySetId"`
}

func (LookupAuthorizationRuleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAuthorizationRuleArgs)(nil)).Elem()
}

// A collection of values returned by getAuthorizationRule.
type LookupAuthorizationRuleResultOutput struct{ *pulumi.OutputState }

func (LookupAuthorizationRuleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAuthorizationRuleResult)(nil)).Elem()
}

func (o LookupAuthorizationRuleResultOutput) ToLookupAuthorizationRuleResultOutput() LookupAuthorizationRuleResultOutput {
	return o
}

func (o LookupAuthorizationRuleResultOutput) ToLookupAuthorizationRuleResultOutputWithContext(ctx context.Context) LookupAuthorizationRuleResultOutput {
	return o
}

// List of child conditions. `conditionType` must be one of `ConditionAndBlock` or `ConditionOrBlock`.
func (o LookupAuthorizationRuleResultOutput) Childrens() GetAuthorizationRuleChildrenArrayOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) []GetAuthorizationRuleChildren { return v.Childrens }).(GetAuthorizationRuleChildrenArrayOutput)
}

// Command sets enforce the specified list of commands that can be executed by a device administrator
func (o LookupAuthorizationRuleResultOutput) CommandSets() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) []string { return v.CommandSets }).(pulumi.StringArrayOutput)
}

// Dictionary attribute name
func (o LookupAuthorizationRuleResultOutput) ConditionAttributeName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) string { return v.ConditionAttributeName }).(pulumi.StringOutput)
}

// Attribute value for condition. Value type is specified in dictionary object.
func (o LookupAuthorizationRuleResultOutput) ConditionAttributeValue() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) string { return v.ConditionAttributeValue }).(pulumi.StringOutput)
}

// Dictionary name
func (o LookupAuthorizationRuleResultOutput) ConditionDictionaryName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) string { return v.ConditionDictionaryName }).(pulumi.StringOutput)
}

// Dictionary value
func (o LookupAuthorizationRuleResultOutput) ConditionDictionaryValue() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) string { return v.ConditionDictionaryValue }).(pulumi.StringOutput)
}

// UUID for condition
func (o LookupAuthorizationRuleResultOutput) ConditionId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) string { return v.ConditionId }).(pulumi.StringOutput)
}

// Indicates whereas this condition is in negate mode
func (o LookupAuthorizationRuleResultOutput) ConditionIsNegate() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) bool { return v.ConditionIsNegate }).(pulumi.BoolOutput)
}

// Equality operator
func (o LookupAuthorizationRuleResultOutput) ConditionOperator() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) string { return v.ConditionOperator }).(pulumi.StringOutput)
}

// Indicates whether the record is the condition itself or a logical aggregation. Logical aggreation indicates that additional conditions are present under the children attribute.
func (o LookupAuthorizationRuleResultOutput) ConditionType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) string { return v.ConditionType }).(pulumi.StringOutput)
}

// Indicates if this rule is the default one
func (o LookupAuthorizationRuleResultOutput) Default() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) bool { return v.Default }).(pulumi.BoolOutput)
}

// The id of the object
func (o LookupAuthorizationRuleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) string { return v.Id }).(pulumi.StringOutput)
}

// Rule name, [Valid characters are alphanumerics, underscore, hyphen, space, period, parentheses]
func (o LookupAuthorizationRuleResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) string { return v.Name }).(pulumi.StringOutput)
}

// Policy set ID
func (o LookupAuthorizationRuleResultOutput) PolicySetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) string { return v.PolicySetId }).(pulumi.StringOutput)
}

// Device admin profiles control the initial login session of the device administrator
func (o LookupAuthorizationRuleResultOutput) Profile() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) string { return v.Profile }).(pulumi.StringOutput)
}

// The rank (priority) in relation to other rules. Lower rank is higher priority.
func (o LookupAuthorizationRuleResultOutput) Rank() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) int { return v.Rank }).(pulumi.IntOutput)
}

// The state that the rule is in. A disabled rule cannot be matched.
func (o LookupAuthorizationRuleResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAuthorizationRuleResult) string { return v.State }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAuthorizationRuleResultOutput{})
}
