// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ise.trustsec;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.ise.Utilities;
import com.pulumi.ise.trustsec.inputs.GetEgressMatrixCellArgs;
import com.pulumi.ise.trustsec.inputs.GetEgressMatrixCellPlainArgs;
import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingArgs;
import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingGroupArgs;
import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingGroupPlainArgs;
import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingPlainArgs;
import com.pulumi.ise.trustsec.inputs.GetSecurityGroupAclArgs;
import com.pulumi.ise.trustsec.inputs.GetSecurityGroupAclPlainArgs;
import com.pulumi.ise.trustsec.inputs.GetSecurityGroupArgs;
import com.pulumi.ise.trustsec.inputs.GetSecurityGroupPlainArgs;
import com.pulumi.ise.trustsec.outputs.GetEgressMatrixCellResult;
import com.pulumi.ise.trustsec.outputs.GetIpToSgtMappingGroupResult;
import com.pulumi.ise.trustsec.outputs.GetIpToSgtMappingResult;
import com.pulumi.ise.trustsec.outputs.GetSecurityGroupAclResult;
import com.pulumi.ise.trustsec.outputs.GetSecurityGroupResult;
import java.util.concurrent.CompletableFuture;

public final class TrustsecFunctions {
    /**
     * This data source can read the TrustSec Egress Matrix Cell.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetEgressMatrixCellArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getEgressMatrixCell(GetEgressMatrixCellArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetEgressMatrixCellResult> getEgressMatrixCell(GetEgressMatrixCellArgs args) {
        return getEgressMatrixCell(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec Egress Matrix Cell.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetEgressMatrixCellArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getEgressMatrixCell(GetEgressMatrixCellArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetEgressMatrixCellResult> getEgressMatrixCellPlain(GetEgressMatrixCellPlainArgs args) {
        return getEgressMatrixCellPlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec Egress Matrix Cell.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetEgressMatrixCellArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getEgressMatrixCell(GetEgressMatrixCellArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetEgressMatrixCellResult> getEgressMatrixCell(GetEgressMatrixCellArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:trustsec/getEgressMatrixCell:getEgressMatrixCell", TypeShape.of(GetEgressMatrixCellResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the TrustSec Egress Matrix Cell.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetEgressMatrixCellArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getEgressMatrixCell(GetEgressMatrixCellArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetEgressMatrixCellResult> getEgressMatrixCellPlain(GetEgressMatrixCellPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:trustsec/getEgressMatrixCell:getEgressMatrixCell", TypeShape.of(GetEgressMatrixCellResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the TrustSec IP to SGT Mapping.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getIpToSgtMapping(GetIpToSgtMappingArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetIpToSgtMappingResult> getIpToSgtMapping() {
        return getIpToSgtMapping(GetIpToSgtMappingArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec IP to SGT Mapping.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getIpToSgtMapping(GetIpToSgtMappingArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetIpToSgtMappingResult> getIpToSgtMappingPlain() {
        return getIpToSgtMappingPlain(GetIpToSgtMappingPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec IP to SGT Mapping.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getIpToSgtMapping(GetIpToSgtMappingArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetIpToSgtMappingResult> getIpToSgtMapping(GetIpToSgtMappingArgs args) {
        return getIpToSgtMapping(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec IP to SGT Mapping.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getIpToSgtMapping(GetIpToSgtMappingArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetIpToSgtMappingResult> getIpToSgtMappingPlain(GetIpToSgtMappingPlainArgs args) {
        return getIpToSgtMappingPlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec IP to SGT Mapping.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getIpToSgtMapping(GetIpToSgtMappingArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetIpToSgtMappingResult> getIpToSgtMapping(GetIpToSgtMappingArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:trustsec/getIpToSgtMapping:getIpToSgtMapping", TypeShape.of(GetIpToSgtMappingResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the TrustSec IP to SGT Mapping.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getIpToSgtMapping(GetIpToSgtMappingArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetIpToSgtMappingResult> getIpToSgtMappingPlain(GetIpToSgtMappingPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:trustsec/getIpToSgtMapping:getIpToSgtMapping", TypeShape.of(GetIpToSgtMappingResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the TrustSec IP to SGT Mapping Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getIpToSgtMappingGroup(GetIpToSgtMappingGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetIpToSgtMappingGroupResult> getIpToSgtMappingGroup() {
        return getIpToSgtMappingGroup(GetIpToSgtMappingGroupArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec IP to SGT Mapping Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getIpToSgtMappingGroup(GetIpToSgtMappingGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetIpToSgtMappingGroupResult> getIpToSgtMappingGroupPlain() {
        return getIpToSgtMappingGroupPlain(GetIpToSgtMappingGroupPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec IP to SGT Mapping Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getIpToSgtMappingGroup(GetIpToSgtMappingGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetIpToSgtMappingGroupResult> getIpToSgtMappingGroup(GetIpToSgtMappingGroupArgs args) {
        return getIpToSgtMappingGroup(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec IP to SGT Mapping Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getIpToSgtMappingGroup(GetIpToSgtMappingGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetIpToSgtMappingGroupResult> getIpToSgtMappingGroupPlain(GetIpToSgtMappingGroupPlainArgs args) {
        return getIpToSgtMappingGroupPlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec IP to SGT Mapping Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getIpToSgtMappingGroup(GetIpToSgtMappingGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetIpToSgtMappingGroupResult> getIpToSgtMappingGroup(GetIpToSgtMappingGroupArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:trustsec/getIpToSgtMappingGroup:getIpToSgtMappingGroup", TypeShape.of(GetIpToSgtMappingGroupResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the TrustSec IP to SGT Mapping Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetIpToSgtMappingGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getIpToSgtMappingGroup(GetIpToSgtMappingGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetIpToSgtMappingGroupResult> getIpToSgtMappingGroupPlain(GetIpToSgtMappingGroupPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:trustsec/getIpToSgtMappingGroup:getIpToSgtMappingGroup", TypeShape.of(GetIpToSgtMappingGroupResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the TrustSec Security Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetSecurityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getSecurityGroup(GetSecurityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetSecurityGroupResult> getSecurityGroup() {
        return getSecurityGroup(GetSecurityGroupArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec Security Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetSecurityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getSecurityGroup(GetSecurityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetSecurityGroupResult> getSecurityGroupPlain() {
        return getSecurityGroupPlain(GetSecurityGroupPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec Security Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetSecurityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getSecurityGroup(GetSecurityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetSecurityGroupResult> getSecurityGroup(GetSecurityGroupArgs args) {
        return getSecurityGroup(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec Security Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetSecurityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getSecurityGroup(GetSecurityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetSecurityGroupResult> getSecurityGroupPlain(GetSecurityGroupPlainArgs args) {
        return getSecurityGroupPlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec Security Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetSecurityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getSecurityGroup(GetSecurityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetSecurityGroupResult> getSecurityGroup(GetSecurityGroupArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:trustsec/getSecurityGroup:getSecurityGroup", TypeShape.of(GetSecurityGroupResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the TrustSec Security Group.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetSecurityGroupArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getSecurityGroup(GetSecurityGroupArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetSecurityGroupResult> getSecurityGroupPlain(GetSecurityGroupPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:trustsec/getSecurityGroup:getSecurityGroup", TypeShape.of(GetSecurityGroupResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the TrustSec Security Group ACL.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetSecurityGroupAclArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getSecurityGroupAcl(GetSecurityGroupAclArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetSecurityGroupAclResult> getSecurityGroupAcl() {
        return getSecurityGroupAcl(GetSecurityGroupAclArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec Security Group ACL.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetSecurityGroupAclArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getSecurityGroupAcl(GetSecurityGroupAclArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetSecurityGroupAclResult> getSecurityGroupAclPlain() {
        return getSecurityGroupAclPlain(GetSecurityGroupAclPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec Security Group ACL.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetSecurityGroupAclArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getSecurityGroupAcl(GetSecurityGroupAclArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetSecurityGroupAclResult> getSecurityGroupAcl(GetSecurityGroupAclArgs args) {
        return getSecurityGroupAcl(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec Security Group ACL.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetSecurityGroupAclArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getSecurityGroupAcl(GetSecurityGroupAclArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetSecurityGroupAclResult> getSecurityGroupAclPlain(GetSecurityGroupAclPlainArgs args) {
        return getSecurityGroupAclPlain(args, InvokeOptions.Empty);
    }
    /**
     * This data source can read the TrustSec Security Group ACL.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetSecurityGroupAclArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getSecurityGroupAcl(GetSecurityGroupAclArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static Output<GetSecurityGroupAclResult> getSecurityGroupAcl(GetSecurityGroupAclArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ise:trustsec/getSecurityGroupAcl:getSecurityGroupAcl", TypeShape.of(GetSecurityGroupAclResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This data source can read the TrustSec Security Group ACL.
     * 
     * ## Example Usage
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.ise.trustsec.TrustsecFunctions;
     * import com.pulumi.ise.trustsec.inputs.GetSecurityGroupAclArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var example = TrustsecFunctions.getSecurityGroupAcl(GetSecurityGroupAclArgs.builder()
     *             .id(&#34;76d24097-41c4-4558-a4d0-a8c07ac08470&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     */
    public static CompletableFuture<GetSecurityGroupAclResult> getSecurityGroupAclPlain(GetSecurityGroupAclPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ise:trustsec/getSecurityGroupAcl:getSecurityGroupAcl", TypeShape.of(GetSecurityGroupAclResult.class), args, Utilities.withVersion(options));
    }
}
