// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * This data source can read the TACACS Command Set.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ise from "@pulumi/ise";
 *
 * const example = ise.tacacs.getCommandSet({
 *     id: "76d24097-41c4-4558-a4d0-a8c07ac08470",
 * });
 * ```
 */
export function getCommandSet(args?: GetCommandSetArgs, opts?: pulumi.InvokeOptions): Promise<GetCommandSetResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ise:tacacs/getCommandSet:getCommandSet", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getCommandSet.
 */
export interface GetCommandSetArgs {
    /**
     * The id of the object
     */
    id?: string;
    /**
     * The name of the TACACS command set
     */
    name?: string;
}

/**
 * A collection of values returned by getCommandSet.
 */
export interface GetCommandSetResult {
    readonly commands: outputs.tacacs.GetCommandSetCommand[];
    /**
     * Description
     */
    readonly description: string;
    /**
     * The id of the object
     */
    readonly id: string;
    /**
     * The name of the TACACS command set
     */
    readonly name: string;
    /**
     * Permit unmatched commands
     */
    readonly permitUnmatched: boolean;
}
/**
 * This data source can read the TACACS Command Set.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ise from "@pulumi/ise";
 *
 * const example = ise.tacacs.getCommandSet({
 *     id: "76d24097-41c4-4558-a4d0-a8c07ac08470",
 * });
 * ```
 */
export function getCommandSetOutput(args?: GetCommandSetOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCommandSetResult> {
    return pulumi.output(args).apply((a: any) => getCommandSet(a, opts))
}

/**
 * A collection of arguments for invoking getCommandSet.
 */
export interface GetCommandSetOutputArgs {
    /**
     * The id of the object
     */
    id?: pulumi.Input<string>;
    /**
     * The name of the TACACS command set
     */
    name?: pulumi.Input<string>;
}
