// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ise.activeDirectory.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetJoinPointPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetJoinPointPlainArgs Empty = new GetJoinPointPlainArgs();

    /**
     * The id of the object
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return The id of the object
     * 
     */
    public String id() {
        return this.id;
    }

    private GetJoinPointPlainArgs() {}

    private GetJoinPointPlainArgs(GetJoinPointPlainArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetJoinPointPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetJoinPointPlainArgs $;

        public Builder() {
            $ = new GetJoinPointPlainArgs();
        }

        public Builder(GetJoinPointPlainArgs defaults) {
            $ = new GetJoinPointPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The id of the object
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public GetJoinPointPlainArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetJoinPointPlainArgs", "id");
            }
            return $;
        }
    }

}
