// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ise.ActiveDirectoryJoin.Inputs
{

    public sealed class PointRewriteRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Required for each rule in the list with no duplication between rules
        /// </summary>
        [Input("rewriteMatch", required: true)]
        public Input<string> RewriteMatch { get; set; } = null!;

        /// <summary>
        /// Required for each rule in the list
        /// </summary>
        [Input("rewriteResult", required: true)]
        public Input<string> RewriteResult { get; set; } = null!;

        /// <summary>
        /// Required for each rule in the list in serial order
        /// </summary>
        [Input("rowId", required: true)]
        public Input<string> RowId { get; set; } = null!;

        public PointRewriteRuleArgs()
        {
        }
        public static new PointRewriteRuleArgs Empty => new PointRewriteRuleArgs();
    }
}
