// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { CellArgs, CellState } from "./cell";
export type Cell = import("./cell").Cell;
export const Cell: typeof import("./cell").Cell = null as any;
utilities.lazyLoad(exports, ["Cell"], () => require("./cell"));

export { GetCellArgs, GetCellResult, GetCellOutputArgs } from "./getCell";
export const getCell: typeof import("./getCell").getCell = null as any;
export const getCellOutput: typeof import("./getCell").getCellOutput = null as any;
utilities.lazyLoad(exports, ["getCell","getCellOutput"], () => require("./getCell"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "ise:TrustsecEgressMatrix/cell:Cell":
                return new Cell(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("ise", "TrustsecEgressMatrix/cell", _module)
