// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ise.ActiveDirectory.Inputs
{

    public sealed class JoinDomainWithAllNodesAdditionalDataArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Additional attribute name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Additional attribute value
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public JoinDomainWithAllNodesAdditionalDataArgs()
        {
        }
        public static new JoinDomainWithAllNodesAdditionalDataArgs Empty => new JoinDomainWithAllNodesAdditionalDataArgs();
    }
}
