// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ise.trustsec.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class MatrixState extends com.pulumi.resources.ResourceArgs {

    public static final MatrixState Empty = new MatrixState();

    /**
     * Policy UUID from which the TrustSec Policies needs to be copied. The default value is empty means it will create a new Matrix without any policies
     * 
     */
    @Import(name="copyPolicyFrom")
    private @Nullable Output<String> copyPolicyFrom;

    /**
     * @return Policy UUID from which the TrustSec Policies needs to be copied. The default value is empty means it will create a new Matrix without any policies
     * 
     */
    public Optional<Output<String>> copyPolicyFrom() {
        return Optional.ofNullable(this.copyPolicyFrom);
    }

    /**
     * DEFCON Level for the TrustSec Matrix
     *   - Choices: `DEFCON1_CRITICAL`, `DEFCON2_SEVERE`, `DEFCON3_SUBSTANTIAL`, `DEFCON4_MODERATE`, `DEFCON5_NORMAL`
     * 
     */
    @Import(name="defconLevel")
    private @Nullable Output<String> defconLevel;

    /**
     * @return DEFCON Level for the TrustSec Matrix
     *   - Choices: `DEFCON1_CRITICAL`, `DEFCON2_SEVERE`, `DEFCON3_SUBSTANTIAL`, `DEFCON4_MODERATE`, `DEFCON5_NORMAL`
     * 
     */
    public Optional<Output<String>> defconLevel() {
        return Optional.ofNullable(this.defconLevel);
    }

    /**
     * Description of the TrustSec Matrix
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Description of the TrustSec Matrix
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Trustsec Matrix Policy Type
     *   - Choices: `TRAFFIC_STEERING_POLICY`, `TRUSTSEC_POLICY`
     * 
     */
    @Import(name="matrixPolicyType")
    private @Nullable Output<String> matrixPolicyType;

    /**
     * @return Trustsec Matrix Policy Type
     *   - Choices: `TRAFFIC_STEERING_POLICY`, `TRUSTSEC_POLICY`
     * 
     */
    public Optional<Output<String>> matrixPolicyType() {
        return Optional.ofNullable(this.matrixPolicyType);
    }

    /**
     * The name of the TrustSec Matrix policy. Must be unique across all matrices.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the TrustSec Matrix policy. Must be unique across all matrices.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private MatrixState() {}

    private MatrixState(MatrixState $) {
        this.copyPolicyFrom = $.copyPolicyFrom;
        this.defconLevel = $.defconLevel;
        this.description = $.description;
        this.matrixPolicyType = $.matrixPolicyType;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(MatrixState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private MatrixState $;

        public Builder() {
            $ = new MatrixState();
        }

        public Builder(MatrixState defaults) {
            $ = new MatrixState(Objects.requireNonNull(defaults));
        }

        /**
         * @param copyPolicyFrom Policy UUID from which the TrustSec Policies needs to be copied. The default value is empty means it will create a new Matrix without any policies
         * 
         * @return builder
         * 
         */
        public Builder copyPolicyFrom(@Nullable Output<String> copyPolicyFrom) {
            $.copyPolicyFrom = copyPolicyFrom;
            return this;
        }

        /**
         * @param copyPolicyFrom Policy UUID from which the TrustSec Policies needs to be copied. The default value is empty means it will create a new Matrix without any policies
         * 
         * @return builder
         * 
         */
        public Builder copyPolicyFrom(String copyPolicyFrom) {
            return copyPolicyFrom(Output.of(copyPolicyFrom));
        }

        /**
         * @param defconLevel DEFCON Level for the TrustSec Matrix
         *   - Choices: `DEFCON1_CRITICAL`, `DEFCON2_SEVERE`, `DEFCON3_SUBSTANTIAL`, `DEFCON4_MODERATE`, `DEFCON5_NORMAL`
         * 
         * @return builder
         * 
         */
        public Builder defconLevel(@Nullable Output<String> defconLevel) {
            $.defconLevel = defconLevel;
            return this;
        }

        /**
         * @param defconLevel DEFCON Level for the TrustSec Matrix
         *   - Choices: `DEFCON1_CRITICAL`, `DEFCON2_SEVERE`, `DEFCON3_SUBSTANTIAL`, `DEFCON4_MODERATE`, `DEFCON5_NORMAL`
         * 
         * @return builder
         * 
         */
        public Builder defconLevel(String defconLevel) {
            return defconLevel(Output.of(defconLevel));
        }

        /**
         * @param description Description of the TrustSec Matrix
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Description of the TrustSec Matrix
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param matrixPolicyType Trustsec Matrix Policy Type
         *   - Choices: `TRAFFIC_STEERING_POLICY`, `TRUSTSEC_POLICY`
         * 
         * @return builder
         * 
         */
        public Builder matrixPolicyType(@Nullable Output<String> matrixPolicyType) {
            $.matrixPolicyType = matrixPolicyType;
            return this;
        }

        /**
         * @param matrixPolicyType Trustsec Matrix Policy Type
         *   - Choices: `TRAFFIC_STEERING_POLICY`, `TRUSTSEC_POLICY`
         * 
         * @return builder
         * 
         */
        public Builder matrixPolicyType(String matrixPolicyType) {
            return matrixPolicyType(Output.of(matrixPolicyType));
        }

        /**
         * @param name The name of the TrustSec Matrix policy. Must be unique across all matrices.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the TrustSec Matrix policy. Must be unique across all matrices.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public MatrixState build() {
            return $;
        }
    }

}
