// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ise.trustsec.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetMatrixResult {
    /**
     * @return Policy UUID from which the TrustSec Policies needs to be copied. The default value is empty means it will create a new Matrix without any policies
     * 
     */
    private String copyPolicyFrom;
    /**
     * @return DEFCON Level for the TrustSec Matrix
     * 
     */
    private String defconLevel;
    /**
     * @return Description of the TrustSec Matrix
     * 
     */
    private String description;
    /**
     * @return The id of the object
     * 
     */
    private String id;
    /**
     * @return Trustsec Matrix Policy Type
     * 
     */
    private String matrixPolicyType;
    /**
     * @return The name of the TrustSec Matrix policy. Must be unique across all matrices.
     * 
     */
    private String name;

    private GetMatrixResult() {}
    /**
     * @return Policy UUID from which the TrustSec Policies needs to be copied. The default value is empty means it will create a new Matrix without any policies
     * 
     */
    public String copyPolicyFrom() {
        return this.copyPolicyFrom;
    }
    /**
     * @return DEFCON Level for the TrustSec Matrix
     * 
     */
    public String defconLevel() {
        return this.defconLevel;
    }
    /**
     * @return Description of the TrustSec Matrix
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return The id of the object
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Trustsec Matrix Policy Type
     * 
     */
    public String matrixPolicyType() {
        return this.matrixPolicyType;
    }
    /**
     * @return The name of the TrustSec Matrix policy. Must be unique across all matrices.
     * 
     */
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMatrixResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String copyPolicyFrom;
        private String defconLevel;
        private String description;
        private String id;
        private String matrixPolicyType;
        private String name;
        public Builder() {}
        public Builder(GetMatrixResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.copyPolicyFrom = defaults.copyPolicyFrom;
    	      this.defconLevel = defaults.defconLevel;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.matrixPolicyType = defaults.matrixPolicyType;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder copyPolicyFrom(String copyPolicyFrom) {
            if (copyPolicyFrom == null) {
              throw new MissingRequiredPropertyException("GetMatrixResult", "copyPolicyFrom");
            }
            this.copyPolicyFrom = copyPolicyFrom;
            return this;
        }
        @CustomType.Setter
        public Builder defconLevel(String defconLevel) {
            if (defconLevel == null) {
              throw new MissingRequiredPropertyException("GetMatrixResult", "defconLevel");
            }
            this.defconLevel = defconLevel;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetMatrixResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetMatrixResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder matrixPolicyType(String matrixPolicyType) {
            if (matrixPolicyType == null) {
              throw new MissingRequiredPropertyException("GetMatrixResult", "matrixPolicyType");
            }
            this.matrixPolicyType = matrixPolicyType;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetMatrixResult", "name");
            }
            this.name = name;
            return this;
        }
        public GetMatrixResult build() {
            final var _resultValue = new GetMatrixResult();
            _resultValue.copyPolicyFrom = copyPolicyFrom;
            _resultValue.defconLevel = defconLevel;
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.matrixPolicyType = matrixPolicyType;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
